---
   - name: capture show output
     hosts: routers
     gather_facts: no
     connection: network_cli

     tasks:
        - name: show run
          ios_command:
           commands:
           - show run
           - show ip route
           - show ip eigrp neighbors
           - show version
         register: config
        - debug: msg="{{ register.stdout }}"
