- name: run show commands
  ansible.netcommon.telnet:
    user: admin
    password: Awr@008
    login_prompt: 'Username: '
    prompts:
    - '[>#]'
    command:
    - terminal length 0
    - show version

