---
- hosts: all
  gather_facts: no
  connection: local
 

  tasks:


  - name: IOS | Show clock
    ios_command:
      commands:
        - show clock
    register: clock

  - debug: msg="{{ clock.stdout }}"
